# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46f6fbc832f9cef32b53f3cc506677a701ea9232bbd3a437eaf93b7a52af6acdadf0004dd84a112c09f9abffae98e55f782022ab2664f71a694ed77f49e57393

test:
  secret_key_base: 2e573bd15a8ee5e86576d144baec2420a9d48fb9a2adf291a1637a2e402d99ecfc67084cdc31b1843e56c5ed8597728870c981d2e1b77f6398d137dd8bfa5ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
